apiVersion: v1

kind: PersistentVolume

metadata:
  name: php-pv
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins/web"

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: php-pvc

spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-server
  labels:
    app: php-server
spec:
  selector:
    matchLabels:
      app: php-server
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-server
        tier: frontend
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: php-server
        ports:
        - containerPort: 80
          name: php-server
        volumeMounts:
        - name: php-storage
          mountPath: /var/www/html/
      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: php-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: php-server
  labels:
    app: php-server
spec:
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: php-server
    tier: frontend
  type: NodePort